version: '3'

services:
  facial-recognition-box:
    build: .
    container_name: facial-recognition-box
    restart: unless-stopped
    privileged: true  # Required for GPIO and camera access
    volumes:
      - ./model:/app/model  # Mount the model directory to persist your face data
    devices:
      - /dev/vchiq:/dev/vchiq  # For camera access
      - /dev/gpiomem:/dev/gpiomem  # For GPIO access
      - /dev/i2c-1:/dev/i2c-1  # For I2C if needed
    environment:
      - PYTHONUNBUFFERED=1  # To see logs immediately